# Generated by Django 5.1.3 on 2024-12-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellerprofile",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="sellerprofile",
            name="tax_id",
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="seller_rating",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="total_products",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="total_sales",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="business_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="business_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="state",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
