# Generated by Django 5.1.3 on 2024-12-12 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_sellerprofile_rating_and_more"),
        ("products", "0002_books_clothing_electronics_shoes_supermarket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="accounts.sellerprofile",
            ),
        ),
    ]
