# Generated by Django 5.1.3 on 2024-12-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Electronics"),
                    (2, "Clothing"),
                    (3, "Shoes"),
                    (4, "Books"),
                    (5, "Supermarket"),
                ]
            ),
        ),
    ]
